// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: proto/document.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message sent from client to server
type DocumentUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // To identify who made the change
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentUpdateRequest) Reset() {
	*x = DocumentUpdateRequest{}
	mi := &file_proto_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentUpdateRequest) ProtoMessage() {}

func (x *DocumentUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentUpdateRequest.ProtoReflect.Descriptor instead.
func (*DocumentUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_document_proto_rawDescGZIP(), []int{0}
}

func (x *DocumentUpdateRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentUpdateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DocumentUpdateRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// Message broadcast from server to clients
type DocumentUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // Who made the change, so clients can ignore their own updates
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentUpdateResponse) Reset() {
	*x = DocumentUpdateResponse{}
	mi := &file_proto_document_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentUpdateResponse) ProtoMessage() {}

func (x *DocumentUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentUpdateResponse.ProtoReflect.Descriptor instead.
func (*DocumentUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_document_proto_rawDescGZIP(), []int{1}
}

func (x *DocumentUpdateResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentUpdateResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DocumentUpdateResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

var File_proto_document_proto protoreflect.FileDescriptor

const file_proto_document_proto_rawDesc = "" +
	"\n" +
	"\x14proto/document.proto\x12\x05proto\"o\n" +
	"\x15DocumentUpdateRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\"p\n" +
	"\x16DocumentUpdateResponse\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId2d\n" +
	"\x0fDocumentService\x12Q\n" +
	"\x0eDocumentStream\x12\x1c.proto.DocumentUpdateRequest\x1a\x1d.proto.DocumentUpdateResponse(\x010\x01BEZCgithub.com/57ajay/module github.com/57ajay/collabwrite-server/protob\x06proto3"

var (
	file_proto_document_proto_rawDescOnce sync.Once
	file_proto_document_proto_rawDescData []byte
)

func file_proto_document_proto_rawDescGZIP() []byte {
	file_proto_document_proto_rawDescOnce.Do(func() {
		file_proto_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_document_proto_rawDesc), len(file_proto_document_proto_rawDesc)))
	})
	return file_proto_document_proto_rawDescData
}

var file_proto_document_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_document_proto_goTypes = []any{
	(*DocumentUpdateRequest)(nil),  // 0: proto.DocumentUpdateRequest
	(*DocumentUpdateResponse)(nil), // 1: proto.DocumentUpdateResponse
}
var file_proto_document_proto_depIdxs = []int32{
	0, // 0: proto.DocumentService.DocumentStream:input_type -> proto.DocumentUpdateRequest
	1, // 1: proto.DocumentService.DocumentStream:output_type -> proto.DocumentUpdateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_document_proto_init() }
func file_proto_document_proto_init() {
	if File_proto_document_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_document_proto_rawDesc), len(file_proto_document_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_document_proto_goTypes,
		DependencyIndexes: file_proto_document_proto_depIdxs,
		MessageInfos:      file_proto_document_proto_msgTypes,
	}.Build()
	File_proto_document_proto = out.File
	file_proto_document_proto_goTypes = nil
	file_proto_document_proto_depIdxs = nil
}
